replicaCount: 1

image:
  repository: ghcr.io/hnodeland/cloud-native-reference-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env:
  port: "8080"
  logLevel: info
  telemetryEnabled: "true"
  otelExporterOtlpEndpoint: http://otel-collector.default.svc.cluster.local:4318
  serviceName: todo-api
